# custom tag that will be added to all saved df's and models.
output_tag:
    'VBF_ggH_BDT'

#.root MC files for all years (sig and bkg) should be kept in this dir:
#Put files in own directory and change location
mc_file_dir:
    '/vols/cms/pas3618/Msci_project/try1/CMSSW_10_6_8/src/HToEE/2017/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/pas3618/Msci_project/try1/CMSSW_10_6_8/src/HToEE/2017/Data/'

mc_file_names:
    sig:
        VBF:
            '2017': 'VBF_M125.root'
    bkg:
        ggH:
            '2017': 'ggH_M125.root'

data_file_names:
        Data:
            '2017': 'Data.root'


#.root files for all years should have these tree paths. Keys should match keys above
proc_to_tree_name:
    VBF: 'Events'
    ggH: 'Events'
    Data: 'Events'

#X variables to train with. Must be in nominal_vars (unless created from existing features)
#Interesting variables are: diphotonPt, leadPhotonEta, subleadPhotonEta
train_vars:
    ['leadPhotonIDMVA','subleadPhotonIDMVA',
    'diphotonMass','diphotonPt',
    'leadPhotonPtOvM','subleadPhotonPtOvM',
    'leadPhotonEta','subleadPhotonEta',
    'dijetMass','dijetAbsDEta','dijetDPhi','diphotonCosPhi',
    'leadJetPUJID','subleadJetPUJID','subsubleadJetPUJID',
    'leadJetPt','leadJetEn','leadJetEta','leadJetPhi',
    'subleadJetPt','subleadJetEn','subleadJetEta','subleadJetPhi',
    'subsubleadJetPt','subsubleadJetEn','subsubleadJetEta','subsubleadJetPhi'
    ] 

vars_to_add:
    #'subsubleadJetCentrality':

#preselection that will be applied to all samples
preselection:    
    'diphotonMass > 100 and diphotonMass < 180 and leadPhotonPtOvM > 0.333 and subleadPhotonPtOvM > 0.25' 

# For purely VBF production mode, can include these following preselection parameters:
#dijetMass>250 and leadJetPt>40 and subleadJetPt>25
